### ISSUE TITLE
Calling ebiten.NewImageFromImage every frame might be problematic in terms of performance

### ISSUE THREAD

**Issue by hajimehoshi** [pokemium/mettaur#3]
https://github.com/pokemium/mettaur/blob/ba03c6cdcc7fe8b56a15546d4b9376c58014c4d4/cmd/main.go#L141

Instead, I recommend

1. creating an offscreen image
2. rendering the result onto the offscreen image by `ReplacePixels`.

Thanks!

**Comment by pokemium** [comment]
I have fixed this as you say. Thank you bro!

**Comment by hajimehoshi** [comment]
No problem. Thank you for using Ebiten, bro!
